language: node_js
node_js:
- stable
cache: npm
script:
- npm run build firefox
- npm run lint:firefox
- npm run build chrome
before_deploy:
- rm packages/*.firefox.xpi.zip
- npm run submit:firefox
deploy:
  provider: releases
  api_key:
    secure: kTGyZQ4SxOIaLNakfk8Uht7QhTlI/qwN463AjEpHRqVaV1kQixn+ex30zTt8XuMZyZa+iAzgZWIF6bbfUmk2064EPnYRZMNB3BPHrk71WDH20Zj5JWSeZgomzTZT6RSa9UcsrJ1oQjHAH017QM5rTZgk8jrBjCaT7GYzQOH7rGpvVeg93jZ/YT19fhaqB3PLG94BTwwJHQUcKfDxzIh53yWg/Psj2rsDc5N4sm9s+XzTHnKKhQb8qcgQtIlHfxi8NRKsTYGvmrkW6fas3JhgOX7C/hesDOTfhv195NMNwDS4dd+GEWEO2s2E+bb4/k1Akzs7hZLRhBPvTjYE+ZED/opqBe7QFe8PnDgE4A7BMkb4SHw3TH+piGo0oHSNbibUzepcGsJcD4sjmD4nn2nrD4csFQCCv5+mA7O6ogYTnF2InTy2XZ7qDU90TrYKDF5JyxcVpX6RvZHIO1KRn491ESZVrX7h7ewWOIvRwufLufC+KKLvyrAHQhI+tw6HD38IfFoTHO7hYd6LrHpeTQ3j3psPLtUvJIwm9iDq/GwuNoHLqlObb7P3YsYdXDDImD354hxoEIONuhWXv7Rrfvx5EY4unZ9XVaeQTqYYlkVu3OAGWn3FqmwBUhxRI/tQBWTiRwIzkxivha3mW19KNcAMaKlR7dazGBzBhQXAJ3AqjtU=
  skip_cleanup: true
  file_glob: true
  file: packages/*
  on:
    repo: jarrodldavis/migrate-guru-notification-webext
    tags: true
notifications:
  slack:
    secure: vRBoj0lBV1hyFKrNNoFg7Lgdw54YdxV7caurW4EblfyFnj9qre/Rfdf419pAyQrYj+nPZsiUyo+rdaqz7ct+0zpaxrfWUHkdS+ex42JL/vEMHlNBoDr8tSXVUXHSGq0sklw0f1yLqQIl/plD9XWl42pc5l5DJoDlg45O+uJTPeeGwc1LwPy9g7Dy5W/jWWH1qGLt3Z49oNL2cKJtKjSJd/90awZxMKAOePesME7aULTU0rcBpGhF6vf3xT1GPToESM5GBb1/AELNgUskPSjO13gCcal34A0jijjxYS3hKsN9gz4L3FuuxC8TCZ4ZPyotJU2OziUfVZUxPfq8Q0rAhUWY1jcNm31+maEQ8XkvHmhfCrdBDImI3Mf/Y04bx79jP4p/vY1mZSh4hK2PJuZlOVRQxfJSqUfEl7rI2UQI6c3Vo1D/D8coRkWCVyTtz4HVpiXxpphiXkQRLRLakLGlscexyKnGF/9tRImJ5pSeDKNGTUFmHGLw8/q+Xea1qa3hoPb/bqA2UuAT51s7ixJ8kO3O6f3/2+DbyFslu7mY82NCAQIleJBVVStHjNmE6TrypFRBH8SC4KDotR4/vf9YSzVR1YsnqzS+ThzjQFWK0UPFo2KXlZ9gyMaM5SdCusxlwWSSt05jCCzIp6e4pvR2UMi5t/6UiQI4EdD4IuHW+Yo=
